version: "3.9"

services:
  postgres-core:
    image: postgres
    mem_reservation: 1024m
    restart: on-failure
    volumes:
      - ./core-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5431:5432"
  minio:
    command: server /home/shared --console-address ":9001"
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"

